server:
  port: 8082
  servlet:
    session:
      timeout: 30m
#spring:
#  application:
#    name: "spring_test"
#  datasource:
#    # allowMultiQueries
#    url: jdbc:mysql://127.0.0.1:3306/spring_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver